# Generated by Django 3.2.6 on 2021-08-16 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('journal', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='journal',
            name='cover',
            field=models.TextField(default='', max_length=255),
        ),
    ]
