# Generated by Django 3.2.6 on 2021-08-16 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('journal', '0002_journal_cover'),
    ]

    operations = [
        migrations.AddField(
            model_name='journal',
            name='url',
            field=models.URLField(default=''),
        ),
        migrations.AlterField(
            model_name='journal',
            name='cover',
            field=models.URLField(),
        ),
    ]
