# Generated by Django 3.2.3 on 2021-08-18 17:06

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('journal', '0004_journal_article_published'),
    ]

    operations = [
        migrations.AlterField(
            model_name='journal',
            name='article_published',
            field=models.DateTimeField(default=datetime.datetime(2021, 8, 18, 17, 6, 28, 246289)),
        ),
    ]
