# Generated by Django 3.2.3 on 2021-09-06 09:20

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('journal', '0005_alter_journal_article_published'),
    ]

    operations = [
        migrations.AddField(
            model_name='journal',
            name='file',
            field=models.FileField(null=True, upload_to='static/carbon06'),
        ),
        migrations.AlterField(
            model_name='journal',
            name='article_published',
            field=models.DateTimeField(default=datetime.datetime(2021, 9, 6, 9, 20, 15, 923473)),
        ),
    ]
