# Generated by Django 3.2.6 on 2021-11-21 14:26

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('journal', '0006_auto_20210906_0920'),
    ]

    operations = [
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('priority', models.PositiveIntegerField()),
            ],
        ),
        migrations.RemoveField(
            model_name='journal',
            name='file',
        ),
        migrations.AlterField(
            model_name='journal',
            name='article_published',
            field=models.DateTimeField(default=datetime.datetime(2021, 11, 21, 17, 26, 28, 138029)),
        ),
        migrations.CreateModel(
            name='Contributor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('surname', models.CharField(max_length=100)),
                ('personal_link', models.CharField(blank=True, max_length=255, null=True)),
                ('bio', models.TextField(blank=True, null=True)),
                ('photo', models.ImageField(upload_to='profiles/')),
                ('role', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='journal.role')),
            ],
        ),
    ]
